version: '3.9'

services:
  backend:
    build: ./nearby-backend
    container_name: nearby-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://your-db-host:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=manuecana

  frontend:
    build: ./nearby-frontend
    container_name: nearby-frontend
    ports:
      - "8081:8081"
