version: "3.9"

services:
  db:
    image: postgres:16
    container_name: nearby-db
    environment:
      POSTGRES_DB: projeto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manuecana
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./nearby-backend/src/main/kotlin/pt/isel/project/nearby/sql/CreateTable.sql:/docker-entrypoint-initdb.d/CreateTable.sql:ro

  backend:
    build: ./nearby-backend
    container_name: nearby-backend
    environment:
      KEY_DB_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: manuecana
    depends_on:
      - db
    expose:
      - "8080"

  frontend:
    build: ./nearby-frontend
    container_name: nearby-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  postgres-data:
